// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD42IVS88GXJslvcId-tIBSlCyqGd_cLiI',
    appId: '1:71240326158:web:5260afc89e611fbed6705f',
    messagingSenderId: '71240326158',
    projectId: 'micro-sugu',
    authDomain: 'micro-sugu.firebaseapp.com',
    storageBucket: 'micro-sugu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSW1inbVAAi5MB-OjlZBvVZV-uWR5gXbE',
    appId: '1:71240326158:android:5d23e4a875c16fa4d6705f',
    messagingSenderId: '71240326158',
    projectId: 'micro-sugu',
    storageBucket: 'micro-sugu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPpYjmx7Y5RKhY6f_dJJYymvhZEGHwW6o',
    appId: '1:71240326158:ios:a4f052e32612ccd6d6705f',
    messagingSenderId: '71240326158',
    projectId: 'micro-sugu',
    storageBucket: 'micro-sugu.firebasestorage.app',
    iosBundleId: 'com.example.sugu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPpYjmx7Y5RKhY6f_dJJYymvhZEGHwW6o',
    appId: '1:71240326158:ios:a4f052e32612ccd6d6705f',
    messagingSenderId: '71240326158',
    projectId: 'micro-sugu',
    storageBucket: 'micro-sugu.firebasestorage.app',
    iosBundleId: 'com.example.sugu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD42IVS88GXJslvcId-tIBSlCyqGd_cLiI',
    appId: '1:71240326158:web:62a8fdbe5c27a233d6705f',
    messagingSenderId: '71240326158',
    projectId: 'micro-sugu',
    authDomain: 'micro-sugu.firebaseapp.com',
    storageBucket: 'micro-sugu.firebasestorage.app',
  );
}
